"""initial exit workflow schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-08 15:22:56.512599
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('TENANT', 'OWNER', 'INSPECTION_AGENCY', 'ADMIN', 'SYSTEM', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_created_at'), 'audit_event', ['created_at'], unique=False)
    op.create_index('ix_audit_event_entity', 'audit_event', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_event_entity_id'), 'audit_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_event_occurred_at'), 'audit_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_event_request_id'), 'audit_event', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_event_retention_until'), 'audit_event', ['retention_until'], unique=False)
    op.create_index(op.f('ix_audit_event_workflow_id'), 'audit_event', ['workflow_id'], unique=False)
    op.create_index('ix_audit_event_workflow_occurred', 'audit_event', ['workflow_id', 'occurred_at'], unique=False)
    op.create_table('exit_workflow',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('property_reference', sa.String(length=64), nullable=True),
    sa.Column('property_address', sa.String(length=512), nullable=True),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('tenant_email', sa.String(length=320), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING_OWNER_APPROVAL', 'OWNER_APPROVED', 'INSPECTION_REQUESTED', 'INSPECTION_SCHEDULED', 'INSPECTION_COMPLETED', 'DAMAGE_REVIEW', 'SETTLEMENT_PENDING', 'SETTLEMENT_COMPLETED', 'NOC_ISSUED', 'COMPLETED', 'CANCELLED', 'REJECTED', name='exit_workflow_status'), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('END_OF_TERM', 'RELOCATION', 'JOB_CHANGE', 'PROPERTY_PURCHASED', 'RENT_INCREASE', 'MAINTENANCE_DISSATISFACTION', 'FINANCIAL_HARDSHIP', 'LANDLORD_REQUEST', 'OTHER', name='exit_reason'), nullable=False),
    sa.Column('reason_details', sa.Text(), nullable=True),
    sa.Column('security_deposit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('documents_uploaded_count', sa.Integer(), nullable=False),
    sa.Column('initiated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('owner_decision_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('owner_decision_by', sa.UUID(), nullable=True),
    sa.Column('owner_rejection_reason', sa.Text(), nullable=True),
    sa.Column('inspection_requested_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('inspection_scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('inspection_completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('damage_review_completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('settlement_completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('noc_issued_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('noc_first_downloaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason <> 'OTHER' OR reason_details IS NOT NULL", name=op.f('ck_exit_workflow_other_reason_requires_details')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_exit_workflow_currency_iso4217')),
    sa.CheckConstraint('security_deposit_amount >= 0', name=op.f('ck_exit_workflow_deposit_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow')),
    sa.UniqueConstraint('reference', name=op.f('uq_exit_workflow_reference'))
    )
    op.create_index(op.f('ix_exit_workflow_contract_id'), 'exit_workflow', ['contract_id'], unique=False)
    op.create_index(op.f('ix_exit_workflow_created_at'), 'exit_workflow', ['created_at'], unique=False)
    op.create_index(op.f('ix_exit_workflow_move_out_date'), 'exit_workflow', ['move_out_date'], unique=False)
    op.create_index(op.f('ix_exit_workflow_owner_id'), 'exit_workflow', ['owner_id'], unique=False)
    op.create_index('ix_exit_workflow_owner_status', 'exit_workflow', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_exit_workflow_property_id'), 'exit_workflow', ['property_id'], unique=False)
    op.create_index(op.f('ix_exit_workflow_status'), 'exit_workflow', ['status'], unique=False)
    op.create_index(op.f('ix_exit_workflow_tenant_id'), 'exit_workflow', ['tenant_id'], unique=False)
    op.create_index('ix_exit_workflow_tenant_status', 'exit_workflow', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_exit_workflow_active_contract', 'exit_workflow', ['contract_id'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED', 'REJECTED')"))
    op.create_index('uq_exit_workflow_active_property', 'exit_workflow', ['property_id'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED', 'REJECTED')"))
    op.create_index('uq_exit_workflow_active_tenant', 'exit_workflow', ['tenant_id'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED', 'REJECTED')"))
    op.create_table('idempotency_record',
    sa.Column('scope', sa.String(length=96), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('scope', 'key', name='pk_idempotency_record')
    )
    op.create_table('notification_log',
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'PUSH', 'SMS', name='notification_channel'), nullable=False),
    sa.Column('template', sa.String(length=96), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_log'))
    )
    op.create_index(op.f('ix_notification_log_created_at'), 'notification_log', ['created_at'], unique=False)
    op.create_index('ix_notification_log_due', 'notification_log', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_notification_log_workflow_id'), 'notification_log', ['workflow_id'], unique=False)
    op.create_table('outbox_event',
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('partition_key', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'FAILED', name='outbox_status'), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event'))
    )
    op.create_index(op.f('ix_outbox_event_aggregate_id'), 'outbox_event', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_event_created_at'), 'outbox_event', ['created_at'], unique=False)
    op.create_index('ix_outbox_event_due', 'outbox_event', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_outbox_event_event_type'), 'outbox_event', ['event_type'], unique=False)
    op.create_table('inspection',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=False),
    sa.Column('agency_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'SLOTS_PROPOSED', 'SCHEDULED', 'COMPLETED', 'CANCELLED', name='inspection_status'), nullable=False),
    sa.Column('request_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('scheduled_slot_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scheduled_by', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('conducted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_no >= 1', name=op.f('ck_inspection_attempt_positive')),
    sa.CheckConstraint('scheduled_end IS NULL OR scheduled_start IS NULL OR scheduled_end > scheduled_start', name=op.f('ck_inspection_schedule_window_valid')),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_inspection_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection')),
    sa.UniqueConstraint('reference', name=op.f('uq_inspection_reference'))
    )
    op.create_index(op.f('ix_inspection_agency_id'), 'inspection', ['agency_id'], unique=False)
    op.create_index(op.f('ix_inspection_created_at'), 'inspection', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspection_status'), 'inspection', ['status'], unique=False)
    op.create_index(op.f('ix_inspection_workflow_id'), 'inspection', ['workflow_id'], unique=False)
    op.create_index('uq_inspection_active_per_workflow', 'inspection', ['workflow_id'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED')"))
    op.create_index('uq_inspection_workflow_attempt', 'inspection', ['workflow_id', 'attempt_no'], unique=True)
    op.create_table('workflow_transition',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('INITIATED', 'PENDING_OWNER_APPROVAL', 'OWNER_APPROVED', 'INSPECTION_REQUESTED', 'INSPECTION_SCHEDULED', 'INSPECTION_COMPLETED', 'DAMAGE_REVIEW', 'SETTLEMENT_PENDING', 'SETTLEMENT_COMPLETED', 'NOC_ISSUED', 'COMPLETED', 'CANCELLED', 'REJECTED', name='exit_workflow_status'), nullable=True),
    sa.Column('to_status', sa.Enum('INITIATED', 'PENDING_OWNER_APPROVAL', 'OWNER_APPROVED', 'INSPECTION_REQUESTED', 'INSPECTION_SCHEDULED', 'INSPECTION_COMPLETED', 'DAMAGE_REVIEW', 'SETTLEMENT_PENDING', 'SETTLEMENT_COMPLETED', 'NOC_ISSUED', 'COMPLETED', 'CANCELLED', 'REJECTED', name='exit_workflow_status'), nullable=False),
    sa.Column('actor_type', sa.Enum('TENANT', 'OWNER', 'INSPECTION_AGENCY', 'ADMIN', 'SYSTEM', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_workflow_transition_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_transition'))
    )
    op.create_index(op.f('ix_workflow_transition_occurred_at'), 'workflow_transition', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_workflow_transition_workflow_id'), 'workflow_transition', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_transition_workflow_occurred', 'workflow_transition', ['workflow_id', 'occurred_at'], unique=False)
    op.create_table('damage_report',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'ACKNOWLEDGED', 'DISPUTED', 'DISPUTE_RESOLVED', 'FINALIZED', name='damage_report_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('inspected_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('inspector_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('assessed_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tenant_reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_review_note', sa.Text(), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('dispute_resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dispute_resolved_by', sa.UUID(), nullable=True),
    sa.Column('dispute_resolution_note', sa.Text(), nullable=True),
    sa.Column('finalized_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('finalized_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.UUID(), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('assessed_total >= 0', name=op.f('ck_damage_report_assessed_total_non_negative')),
    sa.CheckConstraint('finalized_total IS NULL OR finalized_total <= assessed_total', name=op.f('ck_damage_report_finalized_not_above_assessed')),
    sa.CheckConstraint('finalized_total IS NULL OR finalized_total >= 0', name=op.f('ck_damage_report_finalized_non_negative')),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], name=op.f('fk_damage_report_inspection_id_inspection'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_damage_report_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damage_report')),
    sa.UniqueConstraint('inspection_id', name=op.f('uq_damage_report_inspection_id'))
    )
    op.create_index(op.f('ix_damage_report_created_at'), 'damage_report', ['created_at'], unique=False)
    op.create_index(op.f('ix_damage_report_workflow_id'), 'damage_report', ['workflow_id'], unique=False)
    op.create_table('inspection_slot',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ends_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'SELECTED', 'DECLINED', 'EXPIRED', name='slot_status'), nullable=False),
    sa.Column('proposed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_inspection_slot_slot_window_valid')),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], name=op.f('fk_inspection_slot_inspection_id_inspection'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_slot'))
    )
    op.create_index(op.f('ix_inspection_slot_created_at'), 'inspection_slot', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspection_slot_inspection_id'), 'inspection_slot', ['inspection_id'], unique=False)
    op.create_index('ix_inspection_slot_inspection_status', 'inspection_slot', ['inspection_id', 'status'], unique=False)
    op.create_table('damage_line_item',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('STRUCTURAL', 'PAINT_AND_WALLS', 'FLOORING', 'PLUMBING', 'ELECTRICAL', 'APPLIANCES', 'FIXTURES', 'FURNITURE', 'CLEANING', 'KEYS_AND_ACCESS', 'OTHER', name='damage_category'), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'SEVERE', name='damage_severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('assessed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tenant_liable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('assessed_amount >= 0', name=op.f('ck_damage_line_item_line_amount_non_negative')),
    sa.ForeignKeyConstraint(['report_id'], ['damage_report.id'], name=op.f('fk_damage_line_item_report_id_damage_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damage_line_item'))
    )
    op.create_index(op.f('ix_damage_line_item_created_at'), 'damage_line_item', ['created_at'], unique=False)
    op.create_index(op.f('ix_damage_line_item_report_id'), 'damage_line_item', ['report_id'], unique=False)
    op.create_table('settlement',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('damage_report_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', name='settlement_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('security_deposit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deduction_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_due_from_tenant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.UUID(), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('payout_method', sa.Enum('BANK_TRANSFER', 'CHEQUE', 'WALLET', 'NONE', name='payout_method'), nullable=False),
    sa.Column('payout_destination_token', sa.String(length=128), nullable=True),
    sa.Column('payout_destination_masked', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('paid_by', sa.UUID(), nullable=True),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_due_from_tenant >= 0', name=op.f('ck_settlement_balance_non_negative')),
    sa.CheckConstraint('refund_amount = 0 OR balance_due_from_tenant = 0', name=op.f('ck_settlement_refund_and_balance_mutually_exclusive')),
    sa.CheckConstraint('refund_amount = security_deposit_amount - total_deduction_amount + balance_due_from_tenant', name=op.f('ck_settlement_amounts_reconcile')),
    sa.CheckConstraint('refund_amount >= 0', name=op.f('ck_settlement_refund_non_negative')),
    sa.CheckConstraint('security_deposit_amount >= 0', name=op.f('ck_settlement_deposit_non_negative')),
    sa.CheckConstraint('total_deduction_amount >= 0', name=op.f('ck_settlement_deduction_non_negative')),
    sa.ForeignKeyConstraint(['damage_report_id'], ['damage_report.id'], name=op.f('fk_settlement_damage_report_id_damage_report'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_settlement_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement')),
    sa.UniqueConstraint('workflow_id', name=op.f('uq_settlement_workflow_id'))
    )
    op.create_index(op.f('ix_settlement_created_at'), 'settlement', ['created_at'], unique=False)
    op.create_index(op.f('ix_settlement_status'), 'settlement', ['status'], unique=False)
    op.create_table('exit_document',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('damage_line_item_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('EXIT_REQUEST_ATTACHMENT', 'EMIRATES_ID', 'TENANCY_CONTRACT', 'UTILITY_CLEARANCE', 'KEY_HANDOVER', 'DAMAGE_PHOTO', 'INSPECTION_REPORT', 'EXIT_NOC', 'OTHER', name='document_type'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_role', sa.Enum('TENANT', 'OWNER', 'INSPECTION_AGENCY', 'ADMIN', 'SYSTEM', name='actor_type'), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(checksum_sha256) = 64', name=op.f('ck_exit_document_checksum_is_sha256')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_exit_document_size_positive')),
    sa.ForeignKeyConstraint(['damage_line_item_id'], ['damage_line_item.id'], name=op.f('fk_exit_document_damage_line_item_id_damage_line_item'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_exit_document_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_document')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_exit_document_storage_key'))
    )
    op.create_index(op.f('ix_exit_document_created_at'), 'exit_document', ['created_at'], unique=False)
    op.create_index(op.f('ix_exit_document_damage_line_item_id'), 'exit_document', ['damage_line_item_id'], unique=False)
    op.create_index(op.f('ix_exit_document_workflow_id'), 'exit_document', ['workflow_id'], unique=False)
    op.create_index('ix_exit_document_workflow_type', 'exit_document', ['workflow_id', 'document_type'], unique=False)
    op.create_table('exit_noc',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=True),
    sa.Column('noc_number', sa.String(length=24), nullable=False),
    sa.Column('verification_code', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('property_reference', sa.String(length=64), nullable=True),
    sa.Column('property_address', sa.String(length=512), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('security_deposit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deduction_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('first_downloaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_downloaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(content_sha256) = 64', name=op.f('ck_exit_noc_content_hash_is_sha256')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_exit_noc_noc_size_positive')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], name=op.f('fk_exit_noc_settlement_id_settlement'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_exit_noc_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_noc')),
    sa.UniqueConstraint('noc_number', name=op.f('uq_exit_noc_noc_number')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_exit_noc_storage_key')),
    sa.UniqueConstraint('verification_code', name=op.f('uq_exit_noc_verification_code')),
    sa.UniqueConstraint('workflow_id', name=op.f('uq_exit_noc_workflow_id'))
    )
    op.create_index(op.f('ix_exit_noc_created_at'), 'exit_noc', ['created_at'], unique=False)
    op.create_index(op.f('ix_exit_noc_owner_id'), 'exit_noc', ['owner_id'], unique=False)
    op.create_index(op.f('ix_exit_noc_property_id'), 'exit_noc', ['property_id'], unique=False)
    op.create_index(op.f('ix_exit_noc_tenant_id'), 'exit_noc', ['tenant_id'], unique=False)
    op.create_table('payment_transaction',
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('gateway', sa.String(length=64), nullable=False),
    sa.Column('gateway_reference', sa.String(length=128), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('initiated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payment_transaction_amount_non_negative')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], name=op.f('fk_payment_transaction_settlement_id_settlement'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transaction')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payment_transaction_idempotency_key'))
    )
    op.create_index(op.f('ix_payment_transaction_created_at'), 'payment_transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transaction_gateway_reference'), 'payment_transaction', ['gateway_reference'], unique=False)
    op.create_index(op.f('ix_payment_transaction_settlement_id'), 'payment_transaction', ['settlement_id'], unique=False)
    op.create_index('ix_payment_transaction_settlement_status', 'payment_transaction', ['settlement_id', 'status'], unique=False)
    # ### end Alembic commands ###

    # A3 (7-year audit retention): make the audit log append-only at the
    # database level. Application bugs, ad-hoc psql sessions and compromised
    # credentials alike are refused; expiry is handled by a retention job that
    # deletes strictly by retention_until (see AUDIT_RETENTION_DELETE below).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_event_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            IF (TG_OP = 'DELETE') THEN
                IF OLD.retention_until > CURRENT_DATE
                   AND current_setting('exit_workflow.retention_job', true) IS DISTINCT FROM 'on'
                THEN
                    RAISE EXCEPTION
                        'audit_event is append-only: row % is retained until %',
                        OLD.id, OLD.retention_until
                        USING ERRCODE = 'restrict_violation';
                END IF;
                RETURN OLD;
            END IF;
            RAISE EXCEPTION 'audit_event is append-only: UPDATE is not permitted'
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_event_append_only_trigger
        BEFORE UPDATE OR DELETE ON audit_event
        FOR EACH ROW EXECUTE FUNCTION audit_event_append_only();
        """
    )
    # Same protection for the state-transition history.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION workflow_transition_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            IF (TG_OP = 'DELETE') THEN
                RETURN OLD;  -- allowed only via ON DELETE CASCADE from the workflow
            END IF;
            RAISE EXCEPTION 'workflow_transition is append-only: UPDATE is not permitted'
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER workflow_transition_append_only_trigger
        BEFORE UPDATE ON workflow_transition
        FOR EACH ROW EXECUTE FUNCTION workflow_transition_append_only();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_event_append_only_trigger ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS audit_event_append_only()")
    op.execute(
        "DROP TRIGGER IF EXISTS workflow_transition_append_only_trigger ON workflow_transition"
    )
    op.execute("DROP FUNCTION IF EXISTS workflow_transition_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_transaction_settlement_status', table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_settlement_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_gateway_reference'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_created_at'), table_name='payment_transaction')
    op.drop_table('payment_transaction')
    op.drop_index(op.f('ix_exit_noc_tenant_id'), table_name='exit_noc')
    op.drop_index(op.f('ix_exit_noc_property_id'), table_name='exit_noc')
    op.drop_index(op.f('ix_exit_noc_owner_id'), table_name='exit_noc')
    op.drop_index(op.f('ix_exit_noc_created_at'), table_name='exit_noc')
    op.drop_table('exit_noc')
    op.drop_index('ix_exit_document_workflow_type', table_name='exit_document')
    op.drop_index(op.f('ix_exit_document_workflow_id'), table_name='exit_document')
    op.drop_index(op.f('ix_exit_document_damage_line_item_id'), table_name='exit_document')
    op.drop_index(op.f('ix_exit_document_created_at'), table_name='exit_document')
    op.drop_table('exit_document')
    op.drop_index(op.f('ix_settlement_status'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_created_at'), table_name='settlement')
    op.drop_table('settlement')
    op.drop_index(op.f('ix_damage_line_item_report_id'), table_name='damage_line_item')
    op.drop_index(op.f('ix_damage_line_item_created_at'), table_name='damage_line_item')
    op.drop_table('damage_line_item')
    op.drop_index('ix_inspection_slot_inspection_status', table_name='inspection_slot')
    op.drop_index(op.f('ix_inspection_slot_inspection_id'), table_name='inspection_slot')
    op.drop_index(op.f('ix_inspection_slot_created_at'), table_name='inspection_slot')
    op.drop_table('inspection_slot')
    op.drop_index(op.f('ix_damage_report_workflow_id'), table_name='damage_report')
    op.drop_index(op.f('ix_damage_report_created_at'), table_name='damage_report')
    op.drop_table('damage_report')
    op.drop_index('ix_workflow_transition_workflow_occurred', table_name='workflow_transition')
    op.drop_index(op.f('ix_workflow_transition_workflow_id'), table_name='workflow_transition')
    op.drop_index(op.f('ix_workflow_transition_occurred_at'), table_name='workflow_transition')
    op.drop_table('workflow_transition')
    op.drop_index('uq_inspection_workflow_attempt', table_name='inspection')
    op.drop_index('uq_inspection_active_per_workflow', table_name='inspection', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED')"))
    op.drop_index(op.f('ix_inspection_workflow_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_status'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_created_at'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_agency_id'), table_name='inspection')
    op.drop_table('inspection')
    op.drop_index(op.f('ix_outbox_event_event_type'), table_name='outbox_event')
    op.drop_index('ix_outbox_event_due', table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_created_at'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_aggregate_id'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_index(op.f('ix_notification_log_workflow_id'), table_name='notification_log')
    op.drop_index('ix_notification_log_due', table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_created_at'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_table('idempotency_record')
    op.drop_index('uq_exit_workflow_active_tenant', table_name='exit_workflow', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED', 'REJECTED')"))
    op.drop_index('uq_exit_workflow_active_property', table_name='exit_workflow', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED', 'REJECTED')"))
    op.drop_index('uq_exit_workflow_active_contract', table_name='exit_workflow', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'COMPLETED', 'REJECTED')"))
    op.drop_index('ix_exit_workflow_tenant_status', table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_tenant_id'), table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_status'), table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_property_id'), table_name='exit_workflow')
    op.drop_index('ix_exit_workflow_owner_status', table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_owner_id'), table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_move_out_date'), table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_created_at'), table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_contract_id'), table_name='exit_workflow')
    op.drop_table('exit_workflow')
    op.drop_index('ix_audit_event_workflow_occurred', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_workflow_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_retention_until'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_request_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_occurred_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_id'), table_name='audit_event')
    op.drop_index('ix_audit_event_entity', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_created_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###

    # Autogenerate drops tables but not the enum types they created.
    for enum_name in (
        'exit_workflow_status',
        'exit_reason',
        'document_type',
        'actor_type',
        'inspection_status',
        'slot_status',
        'damage_category',
        'damage_severity',
        'damage_report_status',
        'settlement_status',
        'payout_method',
        'payment_status',
        'outbox_status',
        'notification_status',
        'notification_channel',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
