"""T13 step 3 — document upload, listing and download."""

from __future__ import annotations

import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from exit_workflow.core.clock import utcnow
from exit_workflow.core.config import Settings
from exit_workflow.core.errors import ConflictError, ForbiddenError, NotFoundError, ValidationError
from exit_workflow.core.security import Role
from exit_workflow.domain.enums import (
    AGENCY_UPLOADABLE_TYPES,
    TENANT_UPLOADABLE_TYPES,
    ActorType,
    DocumentType,
)
from exit_workflow.models.document import Document
from exit_workflow.models.inspection import DamageLineItem
from exit_workflow.models.workflow import ExitWorkflow
from exit_workflow.services import access
from exit_workflow.services.audit import AuditRecorder
from exit_workflow.services.context import ServiceContext
from exit_workflow.services.events import AggregateType, EventRecorder, EventType
from exit_workflow.services.storage import DocumentStorage, build_key, sanitize_filename, sha256_hex

_OWNER_UPLOADABLE_TYPES = frozenset(
    {DocumentType.KEY_HANDOVER, DocumentType.EXIT_REQUEST_ATTACHMENT, DocumentType.OTHER}
)

#: Types produced by the system itself, never accepted over the upload API.
_SYSTEM_ONLY_TYPES = frozenset({DocumentType.EXIT_NOC})


class DocumentService:
    def __init__(
        self,
        session: AsyncSession,
        settings: Settings,
        ctx: ServiceContext,
        *,
        storage: DocumentStorage,
        audit: AuditRecorder,
        events: EventRecorder,
    ) -> None:
        self._session = session
        self._settings = settings
        self._ctx = ctx
        self._storage = storage
        self._audit = audit
        self._events = events

    def _allowed_types(self) -> frozenset[DocumentType]:
        principal = self._ctx.require_principal()
        match principal.role:
            case Role.TENANT:
                return TENANT_UPLOADABLE_TYPES
            case Role.OWNER:
                return _OWNER_UPLOADABLE_TYPES
            case Role.INSPECTION_AGENCY:
                return AGENCY_UPLOADABLE_TYPES
            case _:
                return frozenset(set(DocumentType) - set(_SYSTEM_ONLY_TYPES))

    async def upload(
        self,
        workflow: ExitWorkflow,
        *,
        document_type: DocumentType,
        filename: str,
        content_type: str,
        data: bytes,
    ) -> Document:
        principal = self._ctx.require_principal()
        access.ensure_can_view(workflow, principal)

        if not workflow.is_active:
            raise ConflictError(
                f"Exit workflow {workflow.reference} is {workflow.status.value}; documents can "
                "no longer be attached."
            )
        if document_type in _SYSTEM_ONLY_TYPES:
            raise ForbiddenError(f"{document_type.value} documents are generated by the system.")
        if document_type not in self._allowed_types():
            raise ForbiddenError(
                f"Role {principal.role.value} may not upload {document_type.value} documents."
            )

        self._validate_payload(content_type, data)

        key = build_key("exit-documents", workflow.id, filename)
        checksum = sha256_hex(data)
        # Store first: an orphaned blob is recoverable, a row pointing at
        # nothing is not.
        await self._storage.put(key, data, content_type)

        document = Document(
            workflow_id=workflow.id,
            document_type=document_type,
            filename=sanitize_filename(filename),
            content_type=content_type,
            size_bytes=len(data),
            storage_key=key,
            checksum_sha256=checksum,
            uploaded_by=principal.subject_id,
            uploaded_by_role=self._ctx.actor_type,
            uploaded_at=utcnow(),
        )
        self._session.add(document)

        if document_type in TENANT_UPLOADABLE_TYPES:
            workflow.documents_uploaded_count = (workflow.documents_uploaded_count or 0) + 1

        self._audit.record(
            self._ctx,
            action="exit_document.uploaded",
            entity_type="exit_document",
            entity_id=document.id,
            workflow_id=workflow.id,
            changes={
                "document_type": document_type,
                "filename": document.filename,
                "size_bytes": document.size_bytes,
                "checksum_sha256": checksum,
            },
        )
        self._events.emit(
            self._ctx,
            event_type=EventType.DOCUMENT_UPLOADED,
            aggregate_type=AggregateType.DOCUMENT,
            aggregate_id=document.id,
            workflow_id=workflow.id,
            payload={
                "document_id": document.id,
                "document_type": document_type.value,
                "reference": workflow.reference,
            },
        )
        # Flush inside the service so constraint violations surface here,
        # where they can be mapped, rather than at commit time.
        await self._session.flush()
        return document

    def _validate_payload(self, content_type: str, data: bytes) -> None:
        if not data:
            raise ValidationError("Uploaded file is empty.")
        if len(data) > self._settings.max_upload_bytes:
            raise ValidationError(
                f"File exceeds the {self._settings.max_upload_bytes} byte limit.",
                extra={"max_bytes": self._settings.max_upload_bytes},
            )
        normalized = (content_type or "").split(";")[0].strip().lower()
        if normalized not in self._settings.allowed_upload_content_types:
            raise ValidationError(
                f"Content type {normalized or 'unknown'} is not accepted.",
                extra={"allowed": self._settings.allowed_upload_content_types},
            )

    async def list_for_workflow(
        self, workflow: ExitWorkflow, *, document_type: DocumentType | None = None
    ) -> list[Document]:
        access.ensure_can_view(workflow, self._ctx.require_principal())
        stmt = select(Document).where(Document.workflow_id == workflow.id)
        if document_type:
            stmt = stmt.where(Document.document_type == document_type)
        return list(
            (await self._session.execute(stmt.order_by(Document.uploaded_at))).scalars().all()
        )

    async def get(self, document_id: uuid.UUID) -> tuple[Document, ExitWorkflow]:
        document = await self._session.get(Document, document_id)
        if document is None:
            raise NotFoundError("Document not found.")
        workflow = await self._session.get(ExitWorkflow, document.workflow_id)
        if workflow is None:  # pragma: no cover - FK guarantees this
            raise NotFoundError("Document not found.")
        access.ensure_can_view(workflow, self._ctx.require_principal())
        return document, workflow

    async def download(self, document_id: uuid.UUID) -> tuple[Document, bytes]:
        document, workflow = await self.get(document_id)
        data = await self._storage.get(document.storage_key)
        if sha256_hex(data) != document.checksum_sha256:
            # Tamper or corruption: refuse to serve rather than hand back
            # something that no longer matches the audited record.
            raise ConflictError(
                "Stored document failed its integrity check and cannot be served.",
                extra={"document_id": str(document.id)},
            )
        self._audit.record(
            self._ctx,
            action="exit_document.downloaded",
            entity_type="exit_document",
            entity_id=document.id,
            workflow_id=workflow.id,
            changes={"filename": document.filename},
        )
        return document, data

    async def attach_photos_to_line_item(
        self,
        workflow: ExitWorkflow,
        line_item: DamageLineItem,
        photo_ids: list[uuid.UUID],
    ) -> list[Document]:
        """Bind previously uploaded damage photos to a report line item."""

        if not photo_ids:
            return []
        stmt = select(Document).where(
            Document.id.in_(photo_ids), Document.workflow_id == workflow.id
        )
        documents = list((await self._session.execute(stmt)).scalars().all())
        found = {d.id for d in documents}
        if missing := [str(p) for p in photo_ids if p not in found]:
            raise ValidationError(
                "Some photo documents do not belong to this exit workflow.",
                extra={"unknown_document_ids": missing},
            )
        for document in documents:
            if document.document_type is not DocumentType.DAMAGE_PHOTO:
                raise ValidationError(
                    f"Document {document.id} is not a DAMAGE_PHOTO.",
                    extra={"document_id": str(document.id)},
                )
            if document.damage_line_item_id not in (None, line_item.id):
                raise ConflictError(
                    f"Document {document.id} is already attached to another line item."
                )
            if document.uploaded_by_role is not ActorType.INSPECTION_AGENCY:
                raise ValidationError(
                    "Damage photos must be uploaded by the inspection agency.",
                    extra={"document_id": str(document.id)},
                )
            # Through the relationship: sets the FK and keeps the in-session
            # line item's photo collection accurate for the response.
            line_item.photos.append(document)
        return documents
