"""initial exit workflow schema

Revision ID: b0b3ecf15270
Revises: 
Create Date: 2026-08-08 09:15:03.693569+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'b0b3ecf15270'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Sequences backing the human-facing identifiers. Allocated with nextval(), which
    # never reuses a value even across rolled-back transactions: gaps are acceptable in
    # a reference number, collisions are not.
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS exit_workflow_reference_seq "
        "AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE"
    )
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS exit_workflow_noc_number_seq "
        "AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exit_workflow',
    sa.Column('reference', sa.String(length=32), nullable=True, comment='Human-facing Workflow ID (T13 step 5), e.g. EXW-2026-000123'),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('property_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tenant_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('owner_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'SUBMITTED', 'OWNER_APPROVED', 'INSPECTION_SLOTS_PROPOSED', 'INSPECTION_SCHEDULED', 'INSPECTION_COMPLETED', 'DAMAGE_REVIEW', 'SETTLEMENT_PENDING', 'SETTLEMENT_PROCESSING', 'SETTLEMENT_COMPLETED', 'NOC_ISSUED', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='exit_workflow_state', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Enum('END_OF_TERM', 'EARLY_TERMINATION', 'RELOCATION', 'JOB_CHANGE', 'PROPERTY_PURCHASE', 'FINANCIAL_HARDSHIP', 'LANDLORD_REQUEST', 'PROPERTY_CONDITION', 'OTHER', name='exit_reason', native_enum=False, create_constraint=True, length=48), nullable=True),
    sa.Column('reason_details', sa.Text(), nullable=True),
    sa.Column('notice_days', sa.BigInteger(), nullable=True),
    sa.Column('notice_waived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'AED'"), nullable=False),
    sa.Column('security_deposit_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tenant_liability_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('initiated_by_role', sa.Enum('TENANT', 'OWNER', 'INSPECTION_AGENCY', 'ADMIN', 'SYSTEM', name='actor_role', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_decision_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('damage_review_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_window_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('noc_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Set for every terminal state, including cancel/reject/expire'),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('DRAFT', 'CANCELLED', 'EXPIRED') OR (move_out_date IS NOT NULL AND reason IS NOT NULL AND reference IS NOT NULL)", name=op.f('ck_exit_workflow_submitted_requires_date_reason_reference')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_exit_workflow_currency_iso4217')),
    sa.CheckConstraint('net_refund_amount IS NULL OR net_refund_amount >= 0', name=op.f('ck_exit_workflow_net_refund_non_negative')),
    sa.CheckConstraint('security_deposit_amount >= 0', name=op.f('ck_exit_workflow_security_deposit_non_negative')),
    sa.CheckConstraint('tenant_liability_amount IS NULL OR tenant_liability_amount >= 0', name=op.f('ck_exit_workflow_tenant_liability_non_negative')),
    sa.CheckConstraint('total_deductions IS NULL OR total_deductions >= 0', name=op.f('ck_exit_workflow_total_deductions_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow')),
    sa.UniqueConstraint('reference', name=op.f('uq_exit_workflow_reference')),
    comment='Tenant exit workflow aggregate (SRS T13, O15, O16, BR-1).'
    )
    op.create_index('ix_exit_workflow_active_tenant', 'exit_workflow', ['tenant_id'], unique=False, postgresql_where=sa.text("state NOT IN ('CANCELLED', 'COMPLETED', 'EXPIRED', 'REJECTED')"))
    op.create_index(op.f('ix_exit_workflow_contract_id'), 'exit_workflow', ['contract_id'], unique=False)
    op.create_index(op.f('ix_exit_workflow_created_at'), 'exit_workflow', ['created_at'], unique=False)
    op.create_index(op.f('ix_exit_workflow_move_out_date'), 'exit_workflow', ['move_out_date'], unique=False)
    op.create_index('ix_exit_workflow_owner_created', 'exit_workflow', ['owner_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_exit_workflow_property_id'), 'exit_workflow', ['property_id'], unique=False)
    op.create_index('ix_exit_workflow_state_updated', 'exit_workflow', ['state', 'updated_at'], unique=False)
    op.create_index('ix_exit_workflow_tenant_created', 'exit_workflow', ['tenant_id', 'created_at', 'id'], unique=False)
    op.create_index('uq_exit_workflow_active_contract', 'exit_workflow', ['contract_id'], unique=True, postgresql_where=sa.text("state NOT IN ('CANCELLED', 'COMPLETED', 'EXPIRED', 'REJECTED')"))
    op.create_index('uq_exit_workflow_active_property', 'exit_workflow', ['property_id'], unique=True, postgresql_where=sa.text("state NOT IN ('CANCELLED', 'COMPLETED', 'EXPIRED', 'REJECTED')"))
    op.create_table('exit_workflow_audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('workflow_reference', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.Enum('TENANT', 'OWNER', 'INSPECTION_AGENCY', 'ADMIN', 'SYSTEM', name='actor_role', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('on_behalf_of', sa.UUID(), nullable=True),
    sa.Column('from_state', sa.String(length=48), nullable=True),
    sa.Column('to_state', sa.String(length=48), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('retention_until', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_audit_log')),
    comment='Append-only audit trail, 7-year retention (SRS A3).'
    )
    op.create_index('ix_exit_workflow_audit_log_actor', 'exit_workflow_audit_log', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_exit_workflow_audit_log_occurred', 'exit_workflow_audit_log', ['occurred_at'], unique=False)
    op.create_index('ix_exit_workflow_audit_log_request', 'exit_workflow_audit_log', ['request_id'], unique=False)
    op.create_index('ix_exit_workflow_audit_log_retention', 'exit_workflow_audit_log', ['retention_until'], unique=False)
    op.create_index('ix_exit_workflow_audit_log_wf', 'exit_workflow_audit_log', ['workflow_id', 'occurred_at'], unique=False)
    op.create_table('exit_workflow_idempotency',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=160), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.BigInteger(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_idempotency')),
    sa.UniqueConstraint('idempotency_key', 'endpoint', name='uq_key_endpoint'),
    comment='Idempotency-Key replay protection for unsafe endpoints.'
    )
    op.create_index('ix_exit_workflow_idempotency_expires', 'exit_workflow_idempotency', ['expires_at'], unique=False)
    op.create_table('exit_workflow_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('partition_key', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'FAILED', 'DEAD_LETTER', name='outbox_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_exit_workflow_outbox_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_outbox')),
    sa.UniqueConstraint('event_id', name=op.f('uq_exit_workflow_outbox_event_id')),
    comment='Transactional outbox relaying exit workflow events to Kafka.'
    )
    op.create_index('ix_exit_workflow_outbox_aggregate', 'exit_workflow_outbox', ['aggregate_id', 'occurred_at'], unique=False)
    op.create_index('ix_exit_workflow_outbox_claimable', 'exit_workflow_outbox', ['available_at', 'id'], unique=False, postgresql_where=sa.text("status IN ('PENDING', 'FAILED')"))
    op.create_index('ix_exit_workflow_outbox_published', 'exit_workflow_outbox', ['published_at'], unique=False, postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.create_table('exit_workflow_document',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('EMIRATES_ID', 'PASSPORT_COPY', 'VISA_COPY', 'TENANCY_CONTRACT', 'DEWA_CLEARANCE', 'CHILLER_CLEARANCE', 'TELECOM_CLEARANCE', 'KEY_HANDOVER_ACKNOWLEDGEMENT', 'BANK_ACCOUNT_PROOF', 'INSPECTION_REPORT', 'DAMAGE_PHOTO', 'EXIT_NOC', 'OTHER', name='document_type', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_role', sa.Enum('TENANT', 'OWNER', 'INSPECTION_AGENCY', 'ADMIN', 'SYSTEM', name='actor_role', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('scan_status', sa.Enum('PENDING', 'CLEAN', 'INFECTED', 'FAILED', 'SKIPPED', name='scan_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(checksum_sha256) = 64', name=op.f('ck_exit_workflow_document_checksum_is_sha256_hex')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_exit_workflow_document_size_positive')),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_exit_workflow_document_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_document')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_exit_workflow_document_storage_key')),
    comment='Metadata for documents attached to an exit workflow.'
    )
    op.create_index('ix_exit_workflow_document_active', 'exit_workflow_document', ['workflow_id', 'document_type'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_exit_workflow_document_created_at'), 'exit_workflow_document', ['created_at'], unique=False)
    op.create_table('exit_workflow_noc',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('noc_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'REVOKED', name='noc_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), server_default=sa.text("'application/pdf'"), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('verification_code', sa.String(length=32), nullable=False),
    sa.Column('verification_url', sa.String(length=512), nullable=False),
    sa.Column('rendered_facts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('download_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'REVOKED') = (revoked_at IS NOT NULL)", name=op.f('ck_exit_workflow_noc_revoked_consistency')),
    sa.CheckConstraint('char_length(checksum_sha256) = 64', name=op.f('ck_exit_workflow_noc_checksum_is_sha256_hex')),
    sa.CheckConstraint('download_count >= 0', name=op.f('ck_exit_workflow_noc_download_count_non_negative')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_exit_workflow_noc_size_positive')),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_exit_workflow_noc_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_noc')),
    sa.UniqueConstraint('noc_number', name=op.f('uq_exit_workflow_noc_noc_number')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_exit_workflow_noc_storage_key')),
    sa.UniqueConstraint('verification_code', name=op.f('uq_exit_workflow_noc_verification_code')),
    sa.UniqueConstraint('workflow_id', name=op.f('uq_exit_workflow_noc_workflow_id')),
    comment='Digital Exit NOC issued on completion of deposit settlement.'
    )
    op.create_index(op.f('ix_exit_workflow_noc_created_at'), 'exit_workflow_noc', ['created_at'], unique=False)
    op.create_index('ix_exit_workflow_noc_issued_at', 'exit_workflow_noc', ['issued_at'], unique=False)
    op.create_table('exit_workflow_settlement',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='settlement_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'AED'"), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('net_refund_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tenant_liability_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalised_by', sa.UUID(), nullable=True),
    sa.Column('owner_note', sa.Text(), nullable=True),
    sa.Column('payout_method', sa.Enum('BANK_TRANSFER', 'CHEQUE', 'WALLET_CREDIT', 'OFFSET_ONLY', name='payout_method', native_enum=False, create_constraint=True, length=48), nullable=True),
    sa.Column('payout_account_ref', sa.String(length=128), nullable=True),
    sa.Column('payout_account_last4', sa.String(length=4), nullable=True),
    sa.Column('payout_account_name', sa.String(length=255), nullable=True),
    sa.Column('payment_provider', sa.String(length=64), nullable=True),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('payment_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('payment_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_initiated_by', sa.UUID(), nullable=True),
    sa.Column('payment_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_attempts', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deposit_amount >= 0', name=op.f('ck_exit_workflow_settlement_deposit_non_negative')),
    sa.CheckConstraint('net_refund_amount = GREATEST(deposit_amount - total_deductions, 0)', name=op.f('ck_exit_workflow_settlement_refund_equals_deposit_minus_deductions')),
    sa.CheckConstraint('net_refund_amount >= 0', name=op.f('ck_exit_workflow_settlement_refund_non_negative')),
    sa.CheckConstraint('payment_attempts >= 0', name=op.f('ck_exit_workflow_settlement_payment_attempts_non_negative')),
    sa.CheckConstraint('tenant_liability_amount = GREATEST(total_deductions - deposit_amount, 0)', name=op.f('ck_exit_workflow_settlement_liability_equals_excess_deductions')),
    sa.CheckConstraint('tenant_liability_amount >= 0', name=op.f('ck_exit_workflow_settlement_liability_non_negative')),
    sa.CheckConstraint('total_deductions >= 0', name=op.f('ck_exit_workflow_settlement_deductions_non_negative')),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_exit_workflow_settlement_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_settlement')),
    sa.UniqueConstraint('payment_idempotency_key', name=op.f('uq_exit_workflow_settlement_payment_idempotency_key')),
    sa.UniqueConstraint('workflow_id', name=op.f('uq_exit_workflow_settlement_workflow_id')),
    comment='Security deposit settlement for an exit workflow (SRS O16).'
    )
    op.create_index(op.f('ix_exit_workflow_settlement_created_at'), 'exit_workflow_settlement', ['created_at'], unique=False)
    op.create_index('ix_exit_workflow_settlement_payment_reference', 'exit_workflow_settlement', ['payment_reference'], unique=False, postgresql_where=sa.text('payment_reference IS NOT NULL'))
    op.create_index('ix_exit_workflow_settlement_status', 'exit_workflow_settlement', ['status'], unique=False)
    op.create_table('exit_workflow_state_transition',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.Enum('DRAFT', 'SUBMITTED', 'OWNER_APPROVED', 'INSPECTION_SLOTS_PROPOSED', 'INSPECTION_SCHEDULED', 'INSPECTION_COMPLETED', 'DAMAGE_REVIEW', 'SETTLEMENT_PENDING', 'SETTLEMENT_PROCESSING', 'SETTLEMENT_COMPLETED', 'NOC_ISSUED', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='from_state', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('to_state', sa.Enum('DRAFT', 'SUBMITTED', 'OWNER_APPROVED', 'INSPECTION_SLOTS_PROPOSED', 'INSPECTION_SCHEDULED', 'INSPECTION_COMPLETED', 'DAMAGE_REVIEW', 'SETTLEMENT_PENDING', 'SETTLEMENT_PROCESSING', 'SETTLEMENT_COMPLETED', 'NOC_ISSUED', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='to_state', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.Enum('TENANT', 'OWNER', 'INSPECTION_AGENCY', 'ADMIN', 'SYSTEM', name='actor_role', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_exit_workflow_state_transition_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_state_transition')),
    comment='Immutable state-change history for the exit workflow.'
    )
    op.create_index('ix_exit_workflow_state_transition_wf', 'exit_workflow_state_transition', ['workflow_id', 'occurred_at'], unique=False)
    op.create_table('exit_workflow_inspection',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=False),
    sa.Column('agency_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'SLOTS_PROPOSED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspection_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('round_number', sa.BigInteger(), server_default=sa.text('1'), nullable=False, comment='Incremented on re-inspection'),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agency_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slots_proposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_by', sa.UUID(), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspector_name', sa.String(length=255), nullable=True),
    sa.Column('inspector_licence_no', sa.String(length=64), nullable=True),
    sa.Column('overall_condition', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', name='property_condition', native_enum=False, create_constraint=True, length=48), nullable=True),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.Column('report_document_id', sa.UUID(), nullable=True),
    sa.Column('assessed_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('round_number >= 1', name=op.f('ck_exit_workflow_inspection_round_number_positive')),
    sa.CheckConstraint('scheduled_end IS NULL OR scheduled_start IS NULL OR scheduled_end > scheduled_start', name=op.f('ck_exit_workflow_inspection_schedule_window_ordered')),
    sa.ForeignKeyConstraint(['report_document_id'], ['exit_workflow_document.id'], name=op.f('fk_exit_workflow_inspection_report_document_id_exit_workflow_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['exit_workflow.id'], name=op.f('fk_exit_workflow_inspection_workflow_id_exit_workflow'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_inspection')),
    sa.UniqueConstraint('workflow_id', name=op.f('uq_exit_workflow_inspection_workflow_id')),
    comment='Third-party inspection engagement (SRS O15).'
    )
    op.create_index(op.f('ix_exit_workflow_inspection_agency_id'), 'exit_workflow_inspection', ['agency_id'], unique=False)
    op.create_index(op.f('ix_exit_workflow_inspection_created_at'), 'exit_workflow_inspection', ['created_at'], unique=False)
    op.create_table('exit_workflow_damage_item',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('category', sa.Enum('DAMAGE', 'CLEANING', 'MISSING_ITEMS', 'UNPAID_RENT', 'UNPAID_UTILITIES', 'MAINTENANCE', 'ADMINISTRATIVE', 'OTHER', name='deduction_category', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'MINOR', 'MODERATE', 'MAJOR', name='damage_severity', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('adjusted_by', sa.UUID(), nullable=True),
    sa.Column('adjusted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adjustment_note', sa.Text(), nullable=True),
    sa.Column('tenant_liable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('dispute_status', sa.Enum('NONE', 'RAISED', 'UPHELD', 'REJECTED', name='dispute_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('disputed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disputed_by', sa.UUID(), nullable=True),
    sa.Column('dispute_resolution_note', sa.Text(), nullable=True),
    sa.Column('dispute_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_resolved_by', sa.UUID(), nullable=True),
    sa.Column('photo_document_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('approved_cost IS NULL OR approved_cost >= 0', name=op.f('ck_exit_workflow_damage_item_approved_cost_non_negative')),
    sa.CheckConstraint('char_length(description) > 0', name=op.f('ck_exit_workflow_damage_item_description_not_blank')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_exit_workflow_damage_item_estimated_cost_non_negative')),
    sa.ForeignKeyConstraint(['inspection_id'], ['exit_workflow_inspection.id'], name=op.f('fk_exit_workflow_damage_item_inspection_id_exit_workflow_inspection'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_damage_item')),
    comment='Damage report line items uploaded by the inspection agency (SRS O16).'
    )
    op.create_index(op.f('ix_exit_workflow_damage_item_created_at'), 'exit_workflow_damage_item', ['created_at'], unique=False)
    op.create_index('ix_exit_workflow_damage_item_disputed', 'exit_workflow_damage_item', ['inspection_id'], unique=False, postgresql_where=sa.text("dispute_status = 'RAISED'"))
    op.create_index('ix_exit_workflow_damage_item_insp', 'exit_workflow_damage_item', ['inspection_id', 'round_number'], unique=False)
    op.create_table('exit_workflow_inspection_slot',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selected_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_exit_workflow_inspection_slot_slot_window_ordered')),
    sa.ForeignKeyConstraint(['inspection_id'], ['exit_workflow_inspection.id'], name=op.f('fk_exit_workflow_inspection_slot_inspection_id_exit_workflow_inspection'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_inspection_slot')),
    comment='Inspection appointment windows offered by the agency.'
    )
    op.create_index(op.f('ix_exit_workflow_inspection_slot_created_at'), 'exit_workflow_inspection_slot', ['created_at'], unique=False)
    op.create_index('ix_exit_workflow_inspection_slot_insp', 'exit_workflow_inspection_slot', ['inspection_id', 'starts_at'], unique=False)
    op.create_index('uq_exit_workflow_inspection_slot_selected', 'exit_workflow_inspection_slot', ['inspection_id'], unique=True, postgresql_where=sa.text('is_selected'))
    op.create_table('exit_workflow_settlement_deduction',
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('damage_item_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('DAMAGE', 'CLEANING', 'MISSING_ITEMS', 'UNPAID_RENT', 'UNPAID_UTILITIES', 'MAINTENANCE', 'ADMINISTRATIVE', 'OTHER', name='deduction_category', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_exit_workflow_settlement_deduction_amount_non_negative')),
    sa.CheckConstraint('char_length(description) > 0', name=op.f('ck_exit_workflow_settlement_deduction_description_not_blank')),
    sa.ForeignKeyConstraint(['damage_item_id'], ['exit_workflow_damage_item.id'], name=op.f('fk_exit_workflow_settlement_deduction_damage_item_id_exit_workflow_damage_item'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['exit_workflow_settlement.id'], name=op.f('fk_exit_workflow_settlement_deduction_settlement_id_exit_workflow_settlement'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_workflow_settlement_deduction')),
    comment='Frozen deduction lines making up a settlement.'
    )
    op.create_index(op.f('ix_exit_workflow_settlement_deduction_created_at'), 'exit_workflow_settlement_deduction', ['created_at'], unique=False)
    op.create_index('ix_exit_workflow_settlement_deduction_stl', 'exit_workflow_settlement_deduction', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exit_workflow_settlement_deduction_stl', table_name='exit_workflow_settlement_deduction')
    op.drop_index(op.f('ix_exit_workflow_settlement_deduction_created_at'), table_name='exit_workflow_settlement_deduction')
    op.drop_table('exit_workflow_settlement_deduction')
    op.drop_index('uq_exit_workflow_inspection_slot_selected', table_name='exit_workflow_inspection_slot', postgresql_where=sa.text('is_selected'))
    op.drop_index('ix_exit_workflow_inspection_slot_insp', table_name='exit_workflow_inspection_slot')
    op.drop_index(op.f('ix_exit_workflow_inspection_slot_created_at'), table_name='exit_workflow_inspection_slot')
    op.drop_table('exit_workflow_inspection_slot')
    op.drop_index('ix_exit_workflow_damage_item_insp', table_name='exit_workflow_damage_item')
    op.drop_index('ix_exit_workflow_damage_item_disputed', table_name='exit_workflow_damage_item', postgresql_where=sa.text("dispute_status = 'RAISED'"))
    op.drop_index(op.f('ix_exit_workflow_damage_item_created_at'), table_name='exit_workflow_damage_item')
    op.drop_table('exit_workflow_damage_item')
    op.drop_index(op.f('ix_exit_workflow_inspection_created_at'), table_name='exit_workflow_inspection')
    op.drop_index(op.f('ix_exit_workflow_inspection_agency_id'), table_name='exit_workflow_inspection')
    op.drop_table('exit_workflow_inspection')
    op.drop_index('ix_exit_workflow_state_transition_wf', table_name='exit_workflow_state_transition')
    op.drop_table('exit_workflow_state_transition')
    op.drop_index('ix_exit_workflow_settlement_status', table_name='exit_workflow_settlement')
    op.drop_index('ix_exit_workflow_settlement_payment_reference', table_name='exit_workflow_settlement', postgresql_where=sa.text('payment_reference IS NOT NULL'))
    op.drop_index(op.f('ix_exit_workflow_settlement_created_at'), table_name='exit_workflow_settlement')
    op.drop_table('exit_workflow_settlement')
    op.drop_index('ix_exit_workflow_noc_issued_at', table_name='exit_workflow_noc')
    op.drop_index(op.f('ix_exit_workflow_noc_created_at'), table_name='exit_workflow_noc')
    op.drop_table('exit_workflow_noc')
    op.drop_index(op.f('ix_exit_workflow_document_created_at'), table_name='exit_workflow_document')
    op.drop_index('ix_exit_workflow_document_active', table_name='exit_workflow_document', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('exit_workflow_document')
    op.drop_index('ix_exit_workflow_outbox_published', table_name='exit_workflow_outbox', postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.drop_index('ix_exit_workflow_outbox_claimable', table_name='exit_workflow_outbox', postgresql_where=sa.text("status IN ('PENDING', 'FAILED')"))
    op.drop_index('ix_exit_workflow_outbox_aggregate', table_name='exit_workflow_outbox')
    op.drop_table('exit_workflow_outbox')
    op.drop_index('ix_exit_workflow_idempotency_expires', table_name='exit_workflow_idempotency')
    op.drop_table('exit_workflow_idempotency')
    op.drop_index('ix_exit_workflow_audit_log_wf', table_name='exit_workflow_audit_log')
    op.drop_index('ix_exit_workflow_audit_log_retention', table_name='exit_workflow_audit_log')
    op.drop_index('ix_exit_workflow_audit_log_request', table_name='exit_workflow_audit_log')
    op.drop_index('ix_exit_workflow_audit_log_occurred', table_name='exit_workflow_audit_log')
    op.drop_index('ix_exit_workflow_audit_log_actor', table_name='exit_workflow_audit_log')
    op.drop_table('exit_workflow_audit_log')
    op.drop_index('uq_exit_workflow_active_property', table_name='exit_workflow', postgresql_where=sa.text("state NOT IN ('CANCELLED', 'COMPLETED', 'EXPIRED', 'REJECTED')"))
    op.drop_index('uq_exit_workflow_active_contract', table_name='exit_workflow', postgresql_where=sa.text("state NOT IN ('CANCELLED', 'COMPLETED', 'EXPIRED', 'REJECTED')"))
    op.drop_index('ix_exit_workflow_tenant_created', table_name='exit_workflow')
    op.drop_index('ix_exit_workflow_state_updated', table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_property_id'), table_name='exit_workflow')
    op.drop_index('ix_exit_workflow_owner_created', table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_move_out_date'), table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_created_at'), table_name='exit_workflow')
    op.drop_index(op.f('ix_exit_workflow_contract_id'), table_name='exit_workflow')
    op.drop_index('ix_exit_workflow_active_tenant', table_name='exit_workflow', postgresql_where=sa.text("state NOT IN ('CANCELLED', 'COMPLETED', 'EXPIRED', 'REJECTED')"))
    op.drop_table('exit_workflow')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS exit_workflow_noc_number_seq")
    op.execute("DROP SEQUENCE IF EXISTS exit_workflow_reference_seq")
